--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions
  labels:
    app: transactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      imagePullSecrets: 
        - name: regcred
      containers:
      - name: transactions
        image: ${IMAGE_RELEASE}
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: transactions
spec:
  type: LoadBalancer
  selector:
    app: transactions
  ports:
  - protocol: TCP
    port: 3000